export const UNKNOWN_ERROR = "Something went wrong, Please try agin.";
export const LOGIN_SUCCESS = "Login Successfully!";
export const REGISTER_SUCCESS = "User Registered Successfully!";
export const VERIFY_SUCCESS = "Email Verified Successfully!";

export const ERROR_OBJECT = { status: false };

export const ADMIN_ROLE = 3;
export const USER_ROLE = 1;
export const EMPLOYEE_ROLE = 2;

export const MENU_ITEMS = [
  {
    _uid: "1",
    name: "Dashboard",
    link: "/dashboard",
    icon: "TbHomeStats",
    targetSegment: "dashboard",
    hasChild: false,
    accessRole: [ADMIN_ROLE, USER_ROLE, EMPLOYEE_ROLE],
    child: [],
  },
  {
    _uid: "2",
    name: "Users",
    link: "/users",
    icon: "FiUsers",
    targetSegment: "users",
    hasChild: true,
    accessRole: [ADMIN_ROLE],
    child: [
      {
        _uid: "2-1",
        name: "Create",
        link: "/users/create",
        icon: "MdCreate",
        targetSegment: "users",
        hasChild: false,
        accessRole: [ADMIN_ROLE],
      },
      {
        _uid: "2-2",
        name: "View",
        link: "/users",
        icon: "GrView",
        targetSegment: "users",
        hasChild: false,
        accessRole: [ADMIN_ROLE],
      },
      {
        _uid: "2-3",
        name: "Restore",
        link: "/users/restore",
        icon: "GrView",
        targetSegment: "users",
        hasChild: false,
        accessRole: [ADMIN_ROLE],
      },
    ],
  },
  {
    _uid: "3",
    name: "Campaign",
    link: "/campaign",
    icon: "GoProjectRoadmap",
    targetSegment: "campaign",
    hasChild: true,
    accessRole: [ADMIN_ROLE, USER_ROLE],
    child: [
      {
        _uid: "3-1",
        name: "Create",
        link: "/campaign/create",
        icon: "MdCreate",
        targetSegment: "campaign",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "3-2",
        name: "View",
        link: "/campaign",
        icon: "GrView",
        targetSegment: "campaign",
        hasChild: false,
        accessRole: [ADMIN_ROLE, USER_ROLE],
      },
    ],
  },
  {
    _uid: "4",
    name: "Social Accounts",
    link: "/social-accounts",
    icon: "MdOutlineAccountTree",
    targetSegment: "social-accounts",
    hasChild: true,
    accessRole: [ADMIN_ROLE, USER_ROLE],
    child: [
      {
        _uid: "4-1",
        name: "Connect",
        link: "/social-accounts/connect",
        icon: "MdCreate",
        targetSegment: "social-accounts",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "4-2",
        name: "View",
        link: "/social-accounts",
        icon: "GrView",
        targetSegment: "social-accounts",
        hasChild: false,
        accessRole: [ADMIN_ROLE, USER_ROLE],
      },
    ],
  },
  {
    _uid: "5",
    name: "Lead Source",
    link: "/lead-source",
    icon: "VscSourceControl",
    targetSegment: "lead-source",
    hasChild: true,
    accessRole: [USER_ROLE, EMPLOYEE_ROLE],
    child: [
      {
        _uid: "5-1",
        name: "Create",
        link: "/lead-source/create",
        icon: "MdCreate",
        targetSegment: "lead-source",
        hasChild: false,
        accessRole: [USER_ROLE, EMPLOYEE_ROLE],
      },
      {
        _uid: "5-2",
        name: "View",
        link: "/lead-source",
        icon: "GrView",
        targetSegment: "lead-source",
        hasChild: false,
        accessRole: [USER_ROLE, EMPLOYEE_ROLE],
      },
    ],
  },
  {
    _uid: "6",
    name: "Lead Segment",
    link: "/lead-segment",
    icon: "PiLineSegments",
    targetSegment: "lead-segment",
    hasChild: true,
    accessRole: [USER_ROLE, EMPLOYEE_ROLE],
    child: [
      {
        _uid: "6-1",
        name: "Create",
        link: "/lead-segment/create",
        icon: "MdCreate",
        targetSegment: "lead-segment",
        hasChild: false,
        accessRole: [USER_ROLE, EMPLOYEE_ROLE],
      },
      {
        _uid: "6-2",
        name: "View",
        link: "/lead-segment",
        icon: "GrView",
        targetSegment: "lead-segment",
        hasChild: false,
        accessRole: [USER_ROLE, EMPLOYEE_ROLE],
      },
    ],
  },
  {
    _uid: "7",
    name: "Lead Manager",
    link: "/lead-manager",
    icon: "MdOutlineManageAccounts",
    targetSegment: "lead-manager",
    hasChild: true,
    accessRole: [ADMIN_ROLE, USER_ROLE, EMPLOYEE_ROLE],
    child: [
      {
        _uid: "7-1",
        name: "Create",
        link: "/lead-manager/create",
        icon: "MdCreate",
        targetSegment: "lead-manager",
        hasChild: false,
        accessRole: [USER_ROLE, EMPLOYEE_ROLE],
      },
      {
        _uid: "7-2",
        name: "View",
        link: "/lead-manager",
        icon: "GrView",
        targetSegment: "lead-manager",
        hasChild: false,
        accessRole: [ADMIN_ROLE, USER_ROLE, EMPLOYEE_ROLE],
      },
      {
        _uid: "7-3",
        name: "Restore",
        link: "/lead-manager/restore",
        icon: "GrView",
        targetSegment: "lead-manager",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
    ],
  },
  {
    _uid: "8",
    name: "Employees",
    link: "/employees",
    icon: "FiUsers",
    targetSegment: "employees",
    hasChild: true,
    accessRole: [USER_ROLE],
    child: [
      {
        _uid: "8-1",
        name: "Create",
        link: "/employees/create",
        icon: "MdCreate",
        targetSegment: "employees",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "8-2",
        name: "View",
        link: "/employees",
        icon: "GrView",
        targetSegment: "employees",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "8-3",
        name: "Restore",
        link: "/employees/restore",
        icon: "GrView",
        targetSegment: "employees",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
    ],
  },
  {
    _uid: "9",
    name: "Marketplace",
    link: "/marketplace",
    icon: "FiShoppingBag",
    targetSegment: "marketplace",
    hasChild: true,
    accessRole: [USER_ROLE],
    child: [
      {
        _uid: "9-1",
        name: "Integrate",
        link: "/marketplace/integrate",
        icon: "MdCreate",
        targetSegment: "marketplace",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "9-2",
        name: "Accounts",
        link: "/marketplace/accounts",
        icon: "GrView",
        targetSegment: "marketplace",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
      {
        _uid: "9-3",
        name: "View",
        link: "/marketplace",
        icon: "GrView",
        targetSegment: "marketplace",
        hasChild: false,
        accessRole: [USER_ROLE],
      },
    ],
  },
  {
    _uid: "10",
    name: "Analytics",
    link: "/analytics",
    icon: "TbReportAnalytics",
    targetSegment: "analytics",
    hasChild: false,
    accessRole: [USER_ROLE],
    child: [],
  },
  {
    _uid: "11",
    name: "Tutorials",
    link: "/tutorials",
    icon: "BiHelpCircle",
    targetSegment: "tutorials",
    hasChild: false,
    accessRole: [ADMIN_ROLE, USER_ROLE, EMPLOYEE_ROLE],
    child: [],
  },
];
